// 侧边模块
export const MODUDLE = [
	{
	  module: 'order',
	  value: 'order',
	  name: '订单',
	  type: 'plate',
	  icon: 'order',
	},
	{
	  module: 'user',
	  value: 'user',
	  name: '用户',
	  type: 'plate',
	  icon: 'user',
	},
	{
	  module: 'service',
	  value: 'service',
	  name: '服务',
	  type: 'plate',
	  icon: 'service',
	},
	{
	  module: 'business',
	  value: 'spread',
	  name: '运营',
	  type: 'plate',
	  icon: 'operation',
	},
	{
		  module: 'space',
	  value: 'space',
	  name: '空间',
	  type: 'plate',
	  icon: '62gongzuokongjian',
	},
	{
		  module: 'talk',
	  value: 'talk',
	  name: '微博',
	  type: 'plate',
	  icon: 'star',
	},
	  {
		  module: 'blog',
	  value: 'blog',
	  name: '博客',
	  type: 'plate',
	  icon: 'star',
	},
	{
	  module: 'tag',
	  value: 'tag/core',
	  name: '标签',
	  type: 'plate',
	  icon: 'tags',
	},
	{
	  module: 'vote',
	  value: 'vote/item',
	  name: '投票',
	  type: 'plate',
	  icon: 'vote',
	},
	{
	  module: 'favorites',
	  value: 'favorites',
	  name: '收藏',
	  type: 'plate',
	  icon: 'industry',
	},
	  {
	  module: 'robot',
	  value: 'robot',
	  name: '机器人',
	  type: 'plate',
	  icon: 'robot',
	},
	  {
	  module: 'commonSense',
	  value: 'commonSense',
	  name: '常识',
	  type: 'plate',
	  icon: 'robot',
	},
	  {
	  module: 'activity',
	  value: 'activity',
	  name: '活动',
	  type: 'plate',
	  icon: 'robot',
	},
	{
	  module: 'three',
	  value: 'three',
	  name: '立体空间',
	  type: 'plate',
	  icon: 'robot',
	},
  ]
  
  // 更多模块
  export const MODUDLE2 = [
	  {
	  module: 'thirdBlog',
	  value: 'thirdBlog',
	  name: '博客收录',
	  type: 'plate',
	  icon: 'blog-1',
	},
	  {
	  module: 'officicalWebsite',
	  value: 'officicalWebsite',
	  name: '官网',
	  type: 'plate',
	  icon: 'website',
	},
	  {
	  module: 'code',
	  value: 'code',
	  name: '基础知识',
	  type: 'plate',
	  icon: 'robot',
	},
	  {
	  module: 'tool',
	  value: 'tool',
	  name: '在线工具',
	  type: 'plate',
	  icon: 'tool',
	},
	  {
	  module: 'file',
	  value: 'file',
	  name: '文件',
	  type: 'plate',
	  icon: 'robot',
	},
	  {
	  module: 'model',
	  value: 'model',
	  name: '大模型',
	  type: 'plate',
	  icon: 'robot',
	},
	  {
	  module: 'tougao',
	  value: 'tougao',
	  name: '投稿',
	  type: 'plate',
	  icon: 'mail',
	},
	  {
	  module: 'questionBank',
	  value: 'questionBank',
	  name: '题库',
	  type: 'plate',
	  icon: 'knowledge',
	},
	  {
	  module: 'trackMap',
	  value: 'trackMap',
	  name: '轨道示意图',
	  type: 'plate',
	  icon: 'blog-1',
	},		
  ]